(function(){
'use strict';
const cloud={enabled:false,configured:false,bootstrapRequired:false,user:null,revision:null,remoteRevision:null,lastError:'',health:null};
const original={renderAuthGate,bootstrapAdminFromForm,loginFromForm,logout,saveSecurityUser,saveSecurityRole,deleteSecurityRole,updateRolePermission,setView};

async function api(path,options={}){
 const init={credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}};
 if(init.body&&typeof init.body!=='string')init.body=JSON.stringify(init.body);
 const r=await fetch(path,init);let data={};try{data=await r.json()}catch{}
 if(!r.ok){const e=new Error(data.message||data.error||`HTTP ${r.status}`);e.status=r.status;e.data=data;throw e}return data
}
function projectKey(){return String(state.campaign.projectKey||state.campaign.id||'').trim()}
function safeSecurityFromMe(data){return {version:1,catalog:Array.isArray(data.catalog)?data.catalog:defaultPermissionCatalog(),roles:Array.isArray(data.roles)?data.roles:defaultRoles(),users:data.user?[data.user]:[],audit:[],settings:data.settings&&typeof data.settings==='object'?data.settings:{sessionMinutes:480}}}
function cloudStatusText(){if(!cloud.health)return 'Détection…';if(!cloud.configured)return `Backend Vercel lié · configuration incomplète${cloud.health.airtableTokenConfigured?'':' · AIRTABLE_TOKEN manquant'}`;if(!cloud.enabled)return 'Cloud indisponible';if(!cloud.user)return cloud.bootstrapRequired?'Cloud prêt · administrateur initial à créer':'Cloud prêt · connexion requise';const rev=cloud.remoteRevision==null?'?':cloud.remoteRevision;return `Cloud actif · ${cloud.user.displayName||cloud.user.username} · révision distante ${rev}`}
function installPanel(){let box=document.getElementById('ajiCloudPanel');if(!box){box=document.createElement('div');box.id='ajiCloudPanel';box.className='card';box.style.marginTop='12px';const view=document.getElementById('view-data');if(view)view.appendChild(box)}if(!box)return;const canView=cloud.user&&can('data.view'),canUpdate=cloud.user&&can('data.update');box.innerHTML=`<div class="head"><div><h2 style="margin:0">Cloud · Vercel + Airtable + GitHub</h2><div class="muted">${esc(cloudStatusText())}</div></div><span class="badge ${cloud.configured?'ok':'warn'}">${cloud.configured?'CONFIGURÉ':'À FINALISER'}</span></div>${cloud.lastError?`<div class="notice error" style="margin-top:10px">${esc(cloud.lastError)}</div>`:''}<div class="actions" style="margin-top:10px"><button class="btn" id="cloudProbeBtn" ${canView?'':'disabled'}>Vérifier le cloud</button><button class="btn" id="cloudLoadBtn" ${canView?'':'disabled'}>Charger état cloud</button><button class="btn primary" id="cloudPublishBtn" ${canUpdate?'':'disabled'}>Publier cet état</button></div><div class="muted" style="margin-top:8px">Aucun remplacement automatique : charger/publier sont des actions explicites avec contrôle de révision.</div>`;document.getElementById('cloudProbeBtn')?.addEventListener('click',cloudProbe);document.getElementById('cloudLoadBtn')?.addEventListener('click',cloudLoad);document.getElementById('cloudPublishBtn')?.addEventListener('click',cloudPublish)}
async function refreshSecuritySnapshot(){if(!cloud.enabled||!cloud.user||!can('security.view'))return;try{const d=await api('/api/security/snapshot');state.security=d.security;currentUserId=cloud.user.id;render()}catch(e){cloud.lastError='Sécurité cloud : '+e.message;installPanel()}}
async function refreshAuth(){if(!cloud.enabled)return false;try{const d=await api('/api/auth/me');cloud.user=d.user;cloud.bootstrapRequired=false;state.security=safeSecurityFromMe(d);currentUserId=d.user.id;try{sessionStorage.removeItem(AUTH_SESSION_KEY)}catch{}render();await cloudProbe(true);return true}catch(e){cloud.user=null;currentUserId='';if(e.status===401){cloud.bootstrapRequired=Boolean(e.data&&e.data.bootstrapRequired);if(cloud.bootstrapRequired)state.security={...emptySecurity(),users:[]};render();return false}cloud.lastError='Authentification cloud indisponible : '+e.message;cloud.enabled=false;render();return false}}
renderAuthGate=function(){if(!cloud.enabled)return original.renderAuthGate();const gate=document.getElementById('authGate'),content=document.getElementById('authGateContent');if(!gate||!content)return;if(cloud.user){gate.classList.add('hidden');return}gate.classList.remove('hidden');if(cloud.bootstrapRequired){content.innerHTML=`<h1>Créer l’administrateur cloud</h1><div class="muted">Compte stocké côté serveur via Airtable ; le mot de passe n’est jamais enregistré dans le HTML.</div><form id="bootstrapAdminForm"><div class="field"><label>Identifiant</label><input name="username" autocomplete="username" required></div><div class="field"><label>Nom affiché</label><input name="displayName" required></div><div class="field"><label>Mot de passe</label><input name="password" type="password" autocomplete="new-password" minlength="10" required></div><div class="field"><label>Confirmer</label><input name="confirmPassword" type="password" autocomplete="new-password" minlength="10" required></div><button class="btn primary" type="submit">Créer l’administrateur</button></form><div class="auth-note">Session signée côté Vercel dans un cookie HttpOnly.</div>`}else{content.innerHTML=`<h1>Connexion AJI Collab Cloud</h1><div class="muted">Authentification serveur Vercel + rôles Airtable.</div><form id="loginForm"><div class="field"><label>Identifiant</label><input name="username" autocomplete="username" required></div><div class="field"><label>Mot de passe</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn primary" type="submit">Se connecter</button></form><div class="auth-note">Les autorisations sont revérifiées côté serveur pour les écritures cloud.</div>`}}
bootstrapAdminFromForm=async function(form){if(!cloud.enabled)return original.bootstrapAdminFromForm(form);const fd=new FormData(form),password=String(fd.get('password')||''),confirm=String(fd.get('confirmPassword')||'');if(password!==confirm)return alert('Les mots de passe ne correspondent pas.');try{await api('/api/auth/bootstrap',{method:'POST',body:{username:String(fd.get('username')||''),displayName:String(fd.get('displayName')||''),password}});await refreshAuth();await refreshSecuritySnapshot()}catch(e){alert('Création administrateur cloud impossible : '+e.message)}};
loginFromForm=async function(form){if(!cloud.enabled)return original.loginFromForm(form);const fd=new FormData(form);try{await api('/api/auth/login',{method:'POST',body:{username:String(fd.get('username')||''),password:String(fd.get('password')||'')}});await refreshAuth();if(can('security.view'))await refreshSecuritySnapshot()}catch(e){alert(e.status===401?'Identifiant ou mot de passe incorrect.':'Connexion cloud impossible : '+e.message)}};
logout=async function(){if(!cloud.enabled)return original.logout();try{await api('/api/auth/logout',{method:'POST'})}catch{}cloud.user=null;currentUserId='';cloud.revision=null;cloud.remoteRevision=null;render()};

saveSecurityUser=async function(form){if(!cloud.enabled)return original.saveSecurityUser(form);if(!requirePermission('security.admin','Gestion utilisateur'))return false;const fd=new FormData(form),existing=securityDialogTargetId?userById(securityDialogTargetId):null,password=String(fd.get('password')||''),confirm=String(fd.get('confirmPassword')||'');if(password!==confirm)return alert('Les mots de passe ne correspondent pas.');const body={username:String(fd.get('username')||'').trim(),displayName:String(fd.get('displayName')||'').trim()};if(existing){body.id=existing.id;if(existing.id!==currentUserId){body.roleId=String(fd.get('roleId')||existing.roleId);body.active=String(fd.get('active'))!=='false'}if(password)body.password=password}else{body.roleId=String(fd.get('roleId')||'utilisateur');body.active=String(fd.get('active'))!=='false';body.password=password}try{await api('/api/security/users',{method:existing?'PATCH':'POST',body});document.getElementById('securityDialog').close();await refreshSecuritySnapshot();return true}catch(e){alert('Utilisateur cloud non enregistré : '+e.message);return false}};
saveSecurityRole=async function(form){if(!cloud.enabled)return original.saveSecurityRole(form);if(!requirePermission('security.admin','Gestion rôle'))return false;const name=String(new FormData(form).get('roleName')||'').trim();try{await api('/api/security/roles',{method:securityDialogTargetId?'PATCH':'POST',body:securityDialogTargetId?{id:securityDialogTargetId,name}:{name}});document.getElementById('securityDialog').close();await refreshSecuritySnapshot();return true}catch(e){alert('Rôle cloud non enregistré : '+e.message);return false}};
deleteSecurityRole=async function(roleId){if(!cloud.enabled)return original.deleteSecurityRole(roleId);const role=roleById(roleId);if(!role||role.system)return alert('Rôle système non supprimable.');if(!confirm('Supprimer le rôle « '+role.name+' » ?'))return false;try{await api('/api/security/roles',{method:'DELETE',body:{id:roleId}});await refreshSecuritySnapshot();return true}catch(e){alert('Suppression cloud refusée : '+e.message);return false}};
updateRolePermission=async function(roleId,permission,checked){if(!cloud.enabled)return original.updateRolePermission(roleId,permission,checked);if(!requirePermission('security.admin','Modification permission'))return false;const role=roleById(roleId);if(!role||role.id==='admin')return false;const set=new Set(role.permissions||[]);checked?set.add(permission):set.delete(permission);try{await api('/api/security/roles',{method:'PATCH',body:{id:roleId,permissions:[...set]}});await refreshSecuritySnapshot();return true}catch(e){alert('Permission cloud refusée : '+e.message);return false}};
setView=function(v){const ok=original.setView(v);if(ok&&cloud.enabled&&v==='security')refreshSecuritySnapshot();return ok};

async function cloudProbe(silent=false){if(!cloud.enabled||!cloud.user||!can('data.view'))return;try{const d=await api('/api/state?projectKey='+encodeURIComponent(projectKey()));cloud.remoteRevision=d.revision;cloud.lastError='';if(!silent)alert('État cloud disponible : révision '+d.revision+'.')}catch(e){if(e.status===404){cloud.remoteRevision=0;cloud.lastError='';if(!silent)alert('Aucun état cloud publié pour ce projet.')}else{cloud.lastError='Lecture cloud : '+e.message;if(!silent)alert(cloud.lastError)}}finally{installPanel()}}
async function cloudLoad(){if(!cloud.enabled||!requirePermission('data.view','Chargement cloud'))return;try{const d=await api('/api/state?projectKey='+encodeURIComponent(projectKey()));if(!confirm(`Charger la révision cloud ${d.revision} et remplacer l’état métier en mémoire/local ?`))return;const candidate={...d.state,security:state.security};validateState(candidate);state=candidate;currentUserId=cloud.user.id;cloud.revision=d.revision;cloud.remoteRevision=d.revision;const current=storageRead(V2_KEY);lastPersistedV2Raw=current.ok?current.value:null;if(!save(false,null,SYSTEM_WRITE_TOKEN))alert('État cloud chargé mais cache local non sauvegardé : '+lastStorageError);render();installPanel()}catch(e){alert(e.status===404?'Aucun état cloud publié.':'Chargement cloud impossible : '+e.message)}}
async function cloudPublish(){if(!cloud.enabled||!requirePermission('data.update','Publication cloud'))return;try{await cloudProbe(true);if((cloud.remoteRevision||0)>0&&cloud.revision!==cloud.remoteRevision)return alert('Une révision cloud existe. Charge-la d’abord avant de publier afin d’éviter un écrasement.');const expected=cloud.revision==null?0:cloud.revision;const d=await api('/api/state',{method:'PUT',body:{projectKey:projectKey(),expectedRevision:expected,state}});cloud.revision=d.revision;cloud.remoteRevision=d.revision;cloud.lastError='';installPanel();alert('État publié dans Airtable : révision '+d.revision+'.')}catch(e){if(e.status===409){cloud.remoteRevision=Number(e.data?.revision||0);cloud.lastError='Conflit cloud : une autre session a publié une nouvelle révision.';installPanel();return alert(cloud.lastError)}alert('Publication cloud impossible : '+e.message)}}

async function init(){installPanel();try{const h=await api('/api/health');cloud.health=h;cloud.configured=Boolean(h.configured);if(!cloud.configured){installPanel();return}cloud.enabled=true;currentUserId='';try{sessionStorage.removeItem(AUTH_SESSION_KEY)}catch{}await refreshAuth();installPanel()}catch(e){cloud.health={};cloud.lastError='Backend cloud non détecté : '+e.message;installPanel()}}
window.AJICollabCloud={state:cloud,init,probe:cloudProbe,load:cloudLoad,publish:cloudPublish};
init();
})();
