const crypto=require('crypto');const zlib=require('zlib');const {config,listAll,createRecords,deleteRecords,getSetting,upsertSetting,eqFormula}=require('./_lib/airtable');const {requireAuth,jsonBody,audit}=require('./_lib/auth');
const CHUNK=45000;const MAX_COMPRESSED=4*1024*1024;
function pointerKey(projectKey){return `state:${projectKey}`}
function stripSecurity(state){const copy=JSON.parse(JSON.stringify(state||{}));delete copy.security;return copy}
async function currentPointer(projectKey){const s=await getSetting(pointerKey(projectKey));if(!s)return {revision:0,checksum:''};try{const v=JSON.parse(s.value||'{}');return {revision:Number(v.revision||0),checksum:String(v.checksum||'')}}catch{return {revision:0,checksum:''}}}
async function rowsFor(projectKey,revision){const f=`AND(${eqFormula('Project Key',projectKey)}, {Revision}=${Number(revision)})`;return listAll(config().state,{filterByFormula:f,sort:{field:'Chunk Index',direction:'asc'}})}
module.exports=async function handler(req,res){try{const permission=req.method==='PUT'?'data.update':'data.view',auth=await requireAuth(req,res,permission);if(!auth)return;const projectKey=String((req.query&&req.query.projectKey)||jsonBody(req).projectKey||'').trim();if(!projectKey||projectKey.length>180)return res.status(400).json({ok:false,error:'PROJECT_KEY_REQUIRED'});if(req.method==='GET'){const ptr=await currentPointer(projectKey);if(!ptr.revision)return res.status(404).json({ok:false,error:'STATE_NOT_FOUND',revision:0});const rows=await rowsFor(projectKey,ptr.revision);if(!rows.length)return res.status(500).json({ok:false,error:'STATE_POINTER_BROKEN'});const encoded=rows.sort((a,b)=>(a.fields?.['Chunk Index']||0)-(b.fields?.['Chunk Index']||0)).map(r=>r.fields?.Payload||'').join('');const compressed=Buffer.from(encoded,'base64');const checksum=crypto.createHash('sha256').update(compressed).digest('hex');if(checksum!==ptr.checksum)return res.status(500).json({ok:false,error:'STATE_CHECKSUM_MISMATCH'});const state=JSON.parse(zlib.gunzipSync(compressed).toString('utf8'));return res.status(200).json({ok:true,revision:ptr.revision,checksum,state})}
 if(req.method==='PUT'){const b=jsonBody(req),expected=Number(b.expectedRevision||0),ptr=await currentPointer(projectKey);if(expected!==ptr.revision)return res.status(409).json({ok:false,error:'REVISION_CONFLICT',revision:ptr.revision});const business=stripSecurity(b.state);if(!business||business.schema!=='aji-collab-v2/2.2.0')return res.status(400).json({ok:false,error:'SCHEMA_INVALID'});const compressed=zlib.gzipSync(Buffer.from(JSON.stringify(business),'utf8'));if(compressed.length>MAX_COMPRESSED)return res.status(413).json({ok:false,error:'STATE_TOO_LARGE',compressedBytes:compressed.length});const encoded=compressed.toString('base64'),chunks=[];for(let i=0;i<encoded.length;i+=CHUNK)chunks.push(encoded.slice(i,i+CHUNK));const revision=ptr.revision+1,checksum=crypto.createHash('sha256').update(compressed).digest('hex');const records=chunks.map((payload,i)=>({'Chunk ID':`${projectKey}:${revision}:${i}`,'Project Key':projectKey,'Revision':revision,'Chunk Index':i,'Total Chunks':chunks.length,'Payload':payload,'Checksum':checksum,'Updated By':auth.user.id}));await createRecords(config().state,records);await upsertSetting(pointerKey(projectKey),JSON.stringify({revision,checksum,at:new Date().toISOString(),by:auth.user.id}));await audit('state.publish',`${projectKey} r${revision}`,auth.user.id);if(ptr.revision){try{const old=await rowsFor(projectKey,ptr.revision);await deleteRecords(config().state,old.map(r=>r.id))}catch(e){console.warn('Nettoyage ancienne révision impossible',e.message)}}return res.status(200).json({ok:true,revision,checksum,chunks:chunks.length,compressedBytes:compressed.length})}
 res.status(405).json({ok:false})}catch(e){console.error(e);res.status(500).json({ok:false,error:'STATE_FAILED',message:e.message})}}
